# Generated by Django 3.0.3 on 2020-02-13 16:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Product', '0003_ratingproduct'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='ratingproduct',
            unique_together={('user_profile', 'product')},
        ),
    ]
