# Generated by Django 3.0.3 on 2020-03-03 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0009_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='stripe_charge_id',
            new_name='source',
        ),
    ]
