# Generated by Django 3.0.3 on 2020-02-26 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Product', '0008_basket'),
        ('Profile', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='Card',
            field=models.ManyToManyField(blank=True, to='Product.Product'),
        ),
    ]
